---
repos:
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.26.3
    hooks:
      - id: check-jsonschema
        name: Validating products
        entry: scripts/check-jsonschema-wrapper
        files: 'products/.*\.md$'
        types_or: []
        verbose: true
